### ISSUE TITLE
Creating Functions project for Python hangs

### ISSUE THREAD

**Issue by swt2c** [Azure/azure-functions-core-tools#1021]
I'm trying to create a Functions project on Ubuntu 18.04 and it just hangs there when I select Python:

```
$ dotnet --version
2.2.103

$ func --version
2.4.317

$ func init
Select a worker runtime: 
1. dotnet
2. node
3. python (preview)
Choose option: 3
python
```

**Comment by ahmelsayed** [comment]
can you run the same command with `CLI_DEBUG=1 func init` and share the output?

**Comment by swt2c** [comment]
```
$ mkdir blah
$ cd blah
$ python3 -m venv env
$ source env/bin/activate
(env) $ CLI_DEBUG=1 func init myfunc
Select a worker runtime: 
1. dotnet
2. node
3. python (preview)
Choose option: 3
python
> python --version
```

**Comment by ahmelsayed** [comment]
what do you get if you run `python --version` from while in that venv? It's trying to get [the version of python](https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/Helpers/PythonHelpers.cs#L109-L134) to verify it's 3.x but it's getting stuck at that command for some reason.

**Comment by swt2c** [comment]
```
(env) $ python --version
Python 3.6.7
```

**Comment by swt2c** [comment]
What's really weird is that it works *some* of the time, but other times it gets stuck.  It works maybe 1/3 of the time.

**Comment by ahmelsayed** [comment]
umm.... okay.. that's interesting. when it gets stuck, if you run `pgrep -al python` from another shell, do you see the `python --version` process there? I'm wondering if the process is actually blocking or if it's exiting but our code is missing that signal some how.

**Comment by swt2c** [comment]
When it's stuck, there is no python process running.

**Comment by swt2c** [comment]
I don't know much about dot net debugging.  Is there some way I can either make the process dump core, or attach a debugger to it and see where it is stuck?

**Comment by ahmelsayed** [comment]
I _think_ I know what's going on. We're registering the exit event handler after calling `.Start()` on the process. If the process terminates very quickly it would cause a race condition and never fire the exit event. #1022 should fix that. It would be awesome if you can give the `.linux-x64.2.4.329.zip` build from here (https://ci.appveyor.com/project/appsvc/azure-functions-cli/builds/22180081/artifacts) a try. You'll need to unzip it somewhere then use `func` from there. Otherwise this change will be in the next release. 

Thanks @swt2c for reporting the issue and for the help debugging through it.

**Comment by swt2c** [comment]
Tested the `.linux-x64.2.4.329.zip`.  `func init` worked in 10/10 tries.  Nice work and thanks for the fast reponse!
