### ISSUE TITLE
Add a user-agent to zipDeploy path

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1096]
We are working to correlate our logs to understand who is publishing from the CLI tools.  Today we can't see when the CLI is publishing via zipDeploy as it doesn't appear any user agent is sent.  Would be good if we could include a user-agent similar to the ArmClient.  Ideally we would include both the fact that it's the CLI and the version of the CLI.  

/cc @dariagrigoriu

**Comment by ColbyTresness** [comment]
@ankitkumarr @fabiocav

**Comment by ColbyTresness** [comment]
@jcookems brings up the valid point that we should always be setting this properly, not just for zipDeploy calls. Is this the case? @ahmelsayed

**Comment by ahmelsayed** [comment]
We should be setting it in most places.

**Comment by ColbyTresness** [comment]
Which ones aren't we? run from package = <SAS URL>?

**Comment by ahmelsayed** [comment]
It's a flag on each `HttpClient`. We don't use the same `HttpClient` in all code paths because there are different flags on it needed for different places. We were setting it on all ARM requests, but not for the /api/zipDeploy ones. A quick search through the code now, the only place we aren't setting it still is with log streaming client. I opened https://github.com/Azure/azure-functions-core-tools/pull/1113
