### ISSUE TITLE
Warnings in log output since upgrading to v2 function in locally run node function

### ISSUE THREAD

**Issue by jdoof** [Azure/azure-functions-core-tools#1317]
We have node function that was running on function run time v1 recently upgrade to v2 run time. Since upgrading to v2 the we are getting lots of errors in log output. We are seeing some logs and not others. 

```
Warning: Unexpected call to 'log' on the context object after function execution has completed. Please check for asynchronous calls that are not awaited or calls to 'done' made before function execution completes
```

We are not seeing the same behaviour on the actual function only on the local run version. Seeing the same of Windows and Macos running from vscode. 

Function is node 8.11 http trigger function. The function its self is behaving as expected but logging is not. 

We are using winston for logging which internally is using the context.log. 

I suspect it might be something to do with logs that called from within an async function.

**Comment by ankitkumarr** [comment]
@mhoeger

**Comment by mhoeger** [comment]
@jdoof - one major difference from v1 to v2 is that v1 uses node version 6 while v2 uses node version 8 or 10, which introduced the `async` keyword. One thing that may have happened is that you introduced the "async" keyword mixed with callbacks which is [not recommended](https://spin.atomicobject.com/2017/04/06/nodejs-promises-callbacks/)

The warning you are seeing describes what is happening - there is a dangerous async pattern somewhere in your code that is making it so that the scope of function execution completes before the work is actually completed. this is also why your logs are not showing up in azure (the logs are no longer tied to the scope of function execution and we cannot associate them correctly).

Example of unawaited asynchronous work with bad pattern:
```javascript
module.exports = function (context) {
    setTimeout(function() {
        context.log("This will log 2 seconds after invocation");
    }, 2000);
    context.done();
    // The function execution is complete, context.done() must always be called when function code execution is complete.
}
```
and corresponding fix:
```javascript
module.exports = function (context) {
    setTimeout(function() {
        context.log("This will log 2 seconds after invocation");
        context.done();
        // overall, the function will take 2 seconds to complete
    }, 2000);
}
```

If the above doesn't match your coding patterns (Ex: you are using promises or async/await instead of callbacks), then can you please post a snippet of code?

**Comment by jdoof** [comment]
@mhoeger Thanks for that I would say more than likely you are correct the code is little more involved than the example so tracking is little tricker. Can I perhaps send you code snippet some other way?

**Comment by mhoeger** [comment]
@jdoof Sure, feel free to email me at mahoeger@microsoft.com !

**Comment by jdoof** [comment]
@mhoeger sent some details via email.

**Comment by mhoeger** [comment]
Looking into the issue, we found that the number of "Warning: Unexpected call to 'log' on the context object" warnings keeps growing as the function app runs for longer. The code is using the npm package [winston](https://www.npmjs.com/package/winston) to aid in logging, and it seems like throughout the lifecycle of the function app, new [transports](https://www.npmjs.com/package/winston#transports) keep getting added, and this means that each call to "log" through winston will call "log" to all registered transports, which includes loggers from previous function executions.

Probably one thing that isn't immediately obvious is what a function app is and how long a function app instance persists. A function app is collectively all of the code you've written in your project, and each "function" can be thought of as just an entry-point into that app. For example, if you created a global variable "foo" and changed its value through the execution of one function, the next execution of a completely different function that reports the value "foo" will reflect the change, IF the function execution are running on the same function app instance. (A single function app instance is what you get when you run locally, for example.) If you read through guidance on [managing connections](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections), this is also why we recommend defining clients on a global scope (because they persist).

Closing this issue as resolved!
