### ISSUE TITLE
handle k8s clusters without KEDA/ScaledObject installed

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-functions-core-tools#1364]
When trying to deploy to a AKS cluster with advanced networking and a azure repository i get:

    func kubernetes deploy --name demo-worker --registry "$registryName.azurecr.io/worker" --secret-name demoregistrysecret --debug
    Running 'docker build -t demoregistry.azurecr.io/worker/demo-worker C:\gitrepos\vso\DigitalRiskOffice\demo-Worker'.....................................................................done
    Running 'docker push demoregistry.azurecr.io/worker/demo-worker'................................................done
    service "demo-worker-http" unchanged
    deployment.apps "demo-worker-http" unchanged
    deployment.apps "demo-worker" unchanged
    error: unable to recognize "STDIN": no matches for kind "ScaledObject" in version "keda.k8s.io/v1alpha1"
    Error running kubectl apply --namespace default -f -.
    output: error: unable to recognize "STDIN": no matches for kind "ScaledObject" in version "keda.k8s.io/v1alpha1"

**Comment by ahmelsayed** [comment]
It assumes you have [KEDA](https://github.com/kedacore/keda) scale controller installed by default in your cluster (which you can do by running `func kubernetes install --namespace ...`.

I think a improvement is to check if the CRD is present before attempting to create it. To workaround this you can add `--ignore-errors` to your deploy command, and it'll skip that error. Keep in mind however that it'll default your deployment to `0` replica count since KEDA takes care of scaling it up and down when there are events. so in addition to `--ignore-errors`, you might wanna add `--min-replicas 1` as well.

**Comment by ahmedelnably** [comment]
@ahmelsayed are we going to use this issue to track the improvement, or we should close this one and track the improvement in another issue

**Comment by crgarcia12** [comment]
Thanks! I think I had issues with the --secret-name
