### ISSUE TITLE
Preserve executable permissions after publish

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-core-tools#1612]

**Comment by ankitkumarr** [comment]
@ahmelsayed added this PR https://github.com/Azure/azure-functions-core-tools/pull/1545
introducing a tool to create archives such that permissions will be preserved in Azure (fuse mount or unzip).

Next step is for me to test it in our environments and make sure it works properly. Once that PR is merged, I need to create a PR to use `go-zip` and create packages using that instead of `DotNetZip` that we use today.

@kulkarnisonia16 / @jeffhollan , do we have a priority assigned to this item, or if it's blocking a customer? Trying to evaluate if I should pull this in the upcoming / current Sprint over some other items.

**Comment by jeffhollan** [comment]
I'd say it's a low P1.  We should definitely get to it this calendar year, ideally in November, but not something that needs to be "drop everything."  Hopefully that helps some.  Happy to give my 2c on the items you would consider dropping if I think it's higher or lower.  As long as we get in during Nov I think it's ok

**Comment by ankitkumarr** [comment]
Assigned Ahmed as well. He already has a PR for a chunk of the work.

**Comment by ankitkumarr** [comment]
I did some tests, and it turns out recent changes in deployment with remote build in place, this is mostly taken care of.

Today, it should work fine for --
1. All Elastic Premium and Dedicated scenarios
2. Linux Consumption with remote build

The only way this does not work is Linux Consumption with `--build local` and `--build-native-deps`. The work we are doing will take care of `--build-native-deps`.

However, `--build local` still has issues as dotnet's `ZipFile.ExtractToDirectory` seems to strip permissions out. I am taking a look at possible options.

**Comment by balag0** [comment]
Is the zip file built using "--build local" mountable?

**Comment by ankitkumarr** [comment]
No it is not. We discussed offline, and I was seeing issues due to an unrelated bug. This is merged and should be available in the next release.
