### ISSUE TITLE
Function deployment through core tools fails if the folder has a space in its name

### ISSUE THREAD

**Issue by fasigpt** [Azure/azure-functions-core-tools#1867]
If the function app is created inside a folder with a space in its name, then the core tools send **zero byte post** to /api/zipdeploy leading to 

Error uploading archive (InternalServerError).
Server Response: {"Message":"An error has occurred.","ExceptionMessage":"Central Directory corrupt.","ExceptionType":"System.IO.InvalidDataException","StackTrace":"   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()\r\n   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)\r\n   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)\r\n   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)\r\n   at Kudu.Services.Deployment.PushDeploymentController.ExtractTriggers(IRepository repository, ZipDeploymentInfo zipDeploymentInfo) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\PushDeploymentController.cs:line 329\r\n   at

**Comment by RolandoMoreno** [comment]
Hi
Related to this, i found another problem when the tools are installed on a folder with a space (in my case was C:\Users\Rolando Moreno\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin) Maybe, my user temp folder was causing the problem (C:\Users\Rolando Moreno\AppData\Local\Temp) 
In order to solve the issue, i rename my user folder to RolandoMoreno.
