### ISSUE TITLE
@xinyi-joffre  Can you share the app name?

### ISSUE THREAD

**Issue by yamiralex** [Azure/azure-functions-core-tools#1956]
@xinyi-joffre  Can you share the app name?

_Originally posted by @divyagandhii in https://github.com/Azure/azure-functions-core-tools/issues/1457#issuecomment-523680185_

I have the same issue , can you helpe please , my app is ome-prod-eastus2-previsao-geracao-energia

**Comment by anthonychu** [comment]
@yamiralex Can you please provide a bit more details about the problem you're having?

**Comment by xinyi-joffre** [comment]
@anthonychu, here is one that I redeployed as linux consumption, but deployments are failing using az functionapp zip deploy: emcb-api-devices-dev

**Comment by xinyi-joffre** [comment]
Possibly related to this one? https://github.com/Azure/azure-cli/issues/12513. Is there any workaround to getting azure function apps and linux working together?

**Comment by balag0** [comment]
@xinyi-joffre Do you mind sharing the exact command you are running? Specifically are you using remote build? I assume this is the cmd that is failing - https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/source?view=azure-cli-latest#az-functionapp-deployment-source-config-zip

**Comment by xinyi-joffre** [comment]
@balag0, yes, we are using:

az functionapp deployment source config-zip --src *.zip -g <group> -n <app name>

No other flags for slots or timeout. The issue looks very close to #12513, where we get `Unknown Error` but no other information. This only occurs with Linux apps, but works on Windows.

Using the func command to deploy not from zip, but from source code is working okay. Other workaround at the moment seems to be using the built-in Azure DevOps task for deploying to function apps, but preference from team is to use Az CLI to run the command so that it is reproducible locally.

**Comment by balag0** [comment]
@xinyi-joffre Sorry I haven't been able to investigate this. 
Can you try setting "--build-remote true" in the az deployment command on the same function app. Let me know if that doesn't work.
