### ISSUE TITLE
Value cannot be null. Parameter name: Provider error on func start

### ISSUE THREAD

**Issue by jclaessens97** [Azure/azure-functions-core-tools#2002]
I have the same issue as #1924 but that issue is closed and I can't interact with it anymore. I'm also on MacOS but cleaning the folder as described in the thread did not work for me. I'm trying to run with `sls offline`.

I searched for a few hours but didn't came across something so I created a stackoverflow question [here](https://stackoverflow.com/questions/61934486/serverless-azure-offline-value-cannot-be-null-parameter-provider). Only now I found out about #1924

**Comment by jclaessens97** [comment]
Oops. Apparently #1995 and #1999 are also related to this issue.

**Comment by anthonychu** [comment]
@jclaessens97 If possible, can you share the project (including the offline files)? It's possible that this is not the same root cause as #1999. Thanks!

**Comment by jclaessens97** [comment]
What do you mean by 'offline files'? The bundle?

**Comment by anthonychu** [comment]
When you run `sls offline`, it should generate some folders/files that are needed to run the app locally. I'm trying to repro by following the quickstart and I'm not able to run `sls offline` because of an incompatible Node version. So if I can somehow see your app, I might be able to figure out what's going on. Thanks.

It looks like the instructions on serverless.com could be out of date. While we figure this out, in the meantime, if you would like to use our supported command line tooling, please take a look at this quickstart: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-javascript

You should be able to get up and running with these commands:

```
func init myapp --worker-runtime javascript
cd myapp
npm install
func new --name HttpExample --template "HTTP trigger"
func host start
```

**Comment by jclaessens97** [comment]
I removed my node_modules and [zipped](https://github.com/Azure/azure-functions-core-tools/files/4663861/AgoraTokenGenerator.zip) the project (since it's a private repo).
It generated host.json and local.settings.json. One oddity I found in the provider section was that on one place they use `region` and on the other `location`. Tried both, didn't work. Thanks for taking the time to investigate this!

I'll take a look at the commands you suggested tomorrow!

**Comment by anthonychu** [comment]
Thanks for the zip file and for reporting this. I was able to repro the issue and found a bug is the Serverless plugin. Please open local.settings.json and set the runtime value to `node` instead of `nodejs`. Created https://github.com/serverless/serverless-azure-functions/issues/467 to track.

**Comment by jclaessens97** [comment]
That does fix it indeed 🙌 Thanks!

To close this, I may suggest to change the message I was getting maybe? Provider was not null so it was very confusing for me 😅
