### ISSUE TITLE
Expose Core Tools as a .NET Core Tool

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-core-tools#2071]
Opening this issue to track the work required to expose installation of the Azure Functions Core Tools as a .NET Core Tool/Global tool

**Comment by fabiocav** [comment]
@anthonychu we can assign this to sprint 80 if you'd like. I'm currently flagging as a P1

**Comment by fabiocav** [comment]
@anthonychu this wasn't assigned to 80, how do you want to prioritize this work?

**Comment by anthonychu** [comment]
@fabiocav Do you know what needs to be done or is there still some discussion before we can move ahead? For me, my main concern is more that we have to maintain another channel for folks to acquire Core Tools and how customers will keep it up to date. Otherwise I'm good with prioritizing it as it needs to be completed before the .NET folks can use it.

**Comment by fabiocav** [comment]
Adding this to sprint 81 for assignment.

**Comment by fabiocav** [comment]
Requirement includes updating the build pipeline to generate artifacts and publish the tool.

**Comment by anthonychu** [comment]
@fabiocav @kashimiz Can you please provide an update on this item? Thanks.

**Comment by pragnagopa** [comment]
@kashimiz did the initial investigation. Need further investigation to update the core tools build. Moving to next sprint.

**Comment by fabiocav** [comment]
@kashimiz should this be moved to sprint 85?

**Comment by fabiocav** [comment]
Completed.
