### ISSUE TITLE
Support for Windows on ARM

### ISSUE THREAD

**Issue by hajekj** [Azure/azure-functions-core-tools#2180]
Since #1680 got closed without further follow-up, I would actually like to learn more about being able to run the Core Tools on ARM-based Surface Pro X.

I can run .NET Core 3.1 fine including VS Code, but like mentioned in the original issue, the Core Tools for some reason install x64-based version of the core tools. Eventually, there could be a build for arm64 so we could run it on ARM machines?

My way around it is using Remote Development Tools and Codespaces, but would love to be able to run it natively.

**Comment by apawast** [comment]
@hajekj thank you for the suggestion. This is not currently on our roadmap, but we will leave this open so we can track any further updates.

**Comment by mohsinonxrm** [comment]
@hajekj , you can build the core tools/CLI yourself for arm or arm64.

In the build.sh script, replace linux-x64 with win10-arm (for 32-bit) or win10-arm64 (for 64-bit)
https://github.com/Azure/azure-functions-core-tools/blob/v3.x/build.sh

If you have the SDK installed, you can also run dotnet publish yourself on the device itself, rather than trying to cross-compile.

I tried the above for Raspberry PI 4 (linux-arm/linux-arm64) and while the tools compile successfully (it is missing the templates, just grab from the github release and drop in the compiled folder). The runtime isn't able to run HTTP trigger functions. I opened an issue back in the day, however didn't get much support. 

In the end, I just ran Azure Function in a docker container on Raspberry PI 4 (you can find plenty of blogs/articles on that).

**Comment by iAmBipinPaul** [comment]
any update on this ?

**Comment by peter-dolkens** [comment]
Interested in this too

**Comment by mohsinonxrm** [comment]
win-arm64 is available in the official release. Give that a try?

https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5198

https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5198/Azure.Functions.Cli.min.win-arm64.4.0.5198.zip

**Comment by andriysavin** [comment]
> win-arm64 is available in the official release. Give that a try?
> 
> https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5198
> 
> https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5198/Azure.Functions.Cli.min.win-arm64.4.0.5198.zip

I'm wondering why there is no an installer for win-arm64, and it's not in the winget repository, and why no docs mentioning arm64 version? I believe Window on ARM deserves better attention.

**Comment by khkh-ms** [comment]
Closing because Win ARM is available for some time now.
