### ISSUE TITLE
macOS Big Sur - Error: Your CLT does not support macOS 11.0.

### ISSUE THREAD

**Issue by jerimiahwelch** [Azure/azure-functions-core-tools#2300]
Is there an ETA on when support is coming for macOS 11.0?

It is alarming to suddenly experience errors when deploying production function apps from vsCode.

Best,
Jerimiah

8:02:42 PM: Running command: "brew upgrade azure-functions-core-tools@2"...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Upgrading 1 outdated package:
azure/functions/azure-functions-core-tools@2 2.7.2936 -> 2.7.3023
==> Upgrading azure/functions/azure-functions-core-tools@2 2.7.2936 -> 2.7.3023 
==> Downloading https://functionscdn.azureedge.net/public/2.7.3023/Azure.Functions.Cli.osx-x64.2.7.3023.zip
Already downloaded: /Users/jerimiahwelch/Library/Caches/Homebrew/downloads/77590aee33dddf514554bbebe91f6745925b7768b30302a8e825e4da3f355819--Azure.Functions.Cli.osx-x64.2.7.3023.zip
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by WebmyneDeveloper** [comment]
I got the same error.

Download latest command-line tools and try again. It's working.

you can download the latest CLT via below link:
https://developer.apple.com/download/more/

**Comment by apawast** [comment]
@jerimiahwelch does the approach suggested by @WebmyneDeveloper work for you?

**Comment by gbd77rc** [comment]
Yes I installed Command Line Tools for Xcode 12.2 release, dated 5th Nov 2020 and I can now install and run the Azure function tools on Mac OS Big Sur.  You still get this warning tho, when installing via VS Code.

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

**Comment by leonardoapolinario** [comment]
For me, brew update-reset solves this issue. 
The command
`brew update-reset`
vanishes the warning message.

I found the solution in 

https://stackoverflow.com/questions/64821648/homebrew-fails-on-macos-big-sur
