### ISSUE TITLE
Use supported TargetFramework

### ISSUE THREAD

**Issue by JamieMagee** [Azure/azure-functions-core-tools#2535]
Both `Azure.Functions.Cli` and `Azure.Functions.Cli.Tests` target the `netcoreapp2.2` `TargetFramework`. 

https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj#L4

[.NET Core 2.2 has been EOL since December 2019](https://dotnet.microsoft.com/download/dotnet/). Please either downgrade to .NET 2.1, which is supported until August 2021, or to .NET Core 3.1, which is supported until December 2022.

**Comment by ankitkumarr** [comment]
@JamieMagee, the current V3 version of Core Tools is in "v3.x" branch, which targets netcoreapp3.1. We need to make v3.x the dev branch, but we haven't done that yet. cc: @fabiocav 

The dev branch points to V2 of Core Tools which is meant for Azure Functions Host v2. For v2, we have to have it targeted "netcoreapp2.2", because that's what Azure Functions Host targets. But V2 is not recommended for Azure Functions, and we default Functions to V3.

Please let us know if this addresses your concerns.

**Comment by JamieMagee** [comment]
Yep! That's great thank you.
