### ISSUE TITLE
npm latest is 2.7.3188 but is 7 months old?

### ISSUE THREAD

**Issue by diberry** [Azure/azure-functions-core-tools#2655]
Can you change the version that is marked latest in NPM to either 3 or 4?

**Comment by anthonychu** [comment]
duplicate #2665

**Comment by anthonychu** [comment]
@fabiocav @apawast Can we consider pointing latest to the latest stable version? I know in the past we didn't do this because it's a breaking change for CI processes that might install it without a version number. But this is causing customers to install older versions. This is not how most people expect npm packages to work.

**Comment by fabiocav** [comment]
We can. If you want to push that change and we're all in agreement, that's a simple change to make.

**Comment by fabiocav** [comment]
This is now done. Latest now points to the latest 3.0/stable release.
