### ISSUE TITLE
V3 marked as latest

### ISSUE THREAD

**Issue by ReschAndr** [Azure/azure-functions-core-tools#3118]
On Github Releases a version of the v3 core tools is marked as latest.

https://github.com/Azure/azure-functions-core-tools/releases

![image](https://user-images.githubusercontent.com/23379723/183844049-4c49fd65-7e3a-41dc-a757-12e4cfa07554.png)

**Comment by ejizba** [comment]
Hi @ReschAndr we support both major versions, meaning we regularly publish releases for both v3 and v4 of core tools. As far as I know, GitHub will mark a release with "Latest" based on the timestamp, not based on the version. Since we did a v3 release most recently, it will be "Latest" until we do a v4 release. If you know of a way to fix this on GitHub let me know, but I don't think it's possible

**Comment by ReschAndr** [comment]
Sorry I don't know how to fix this on Github. But as far as I can see there is a more recent release for the v4 version than the one marked as latest from the v3 version.
As you can see below the [4.0.4670](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.4670) was released 13 days ago. The [3.0.4669](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.4669) was released already 2 days prior to that.

![image](https://user-images.githubusercontent.com/23379723/184078396-d7304444-a335-447d-bd7d-8a541e5ca1e1.png)

**Comment by ejizba** [comment]
Interesting, although I can guess why that happened. As a bit of background, when we first create a release we check this checkbox:
![Screen Shot 2022-08-11 at 10 33 58 AM](https://user-images.githubusercontent.com/11282622/184197149-b20645d1-6c0d-45dc-ba5e-f9544e8fed2a.png)

We do that for a little while to test the new release before we mark it production ready and before we release it to all channels (like brew, npm, apt, etc.). I believe GitHub determines "Latest" based on when that checkbox was first unchecked, not when the release was created. The v3 release took longer to test this time and we unchecked the box more recently.

This should be resolved once we finish testing the new v4.0.4704 release and mark it as production ready. That being said, v3 may occasionally be marked as "Latest" due to how GitHub handles releases. It's a quirk of GitHub and there's nothing we can do about it since we support multiple major versions at a time. As noted [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions) v3 will no longer be supported starting on December 3, 2022 so that will reduce the frequency of this happening.
