### ISSUE TITLE
Incompatible Node.js version (v19.4.0).

### ISSUE THREAD

**Issue by pguardiario** [Azure/azure-functions-core-tools#3283]
Do I really have to downgrade my node just to test a an azure function? This feels really mean.

**Comment by ejizba** [comment]
Hi @pguardiario this was fixed in the Node.js worker already: https://github.com/Azure/azure-functions-nodejs-worker/pull/645. It will be included in the next release of core tools which is hopefully coming very soon

Unfortunately there was quite a delay between the PR being merged and the change making it to core tools. If https://github.com/Azure/azure-functions-core-tools/issues/2122 was addressed it would be faster, but I'm not sure when that would happen.

**Comment by ejizba** [comment]
This should be fixed in core tools [v4.0.5030](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5030)
