### ISSUE TITLE
Functions app fails to start/hangs indefinitely due to extensionsBundle config 

### ISSUE THREAD

**Issue by kylekirkby** [Azure/azure-functions-core-tools#3364]
Whilst using this configuration in `host.json`:

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  }
}
```

`func start` failed to start the azure functions API.  However, after a lot of debugging, the fix I found was to upgrade the `extensionsBundle` to `[4.0.0, 5.0.0)`.

It would be great if anyone has any idea as to what has caused this to suddenly stop working. 

OS Version: Windows 10
Azure Function Core Tools Version: 4.0.5030
Node Version: v18.14.1

**Comment by swatDong** [comment]
I also met this when the network is not very well.
In addition, I found that `func start` will try to download `Microsoft.Azure.Functions.ExtensionBundle` twice:
1. The first one is the latest version (in my case it's 4.5.0). I found this because finally I see it under my `${USER_HOME}\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\`. And **there's no log/output during this downloading**, thus looks like it's hanging.
2. The second one is the one matched by the version in `host.json`. This one has verbose log so I can see what's going one.


**Is there anyway to skip the first download or at least add log to show it's downloading something?**


OS Version: Windows 10
Azure Function Core Tools Version: 4.0.5198
Node Version: v18.16.0

**Comment by gsouf** [comment]
@khkh-ms is it expected to have no logs and the feeling that it's not working

**Comment by ldibanyez** [comment]
> `func start` failed to start the azure functions API. However, after a lot of debugging, the fix I found was to upgrade the `extensionsBundle` to `[4.0.0, 5.0.0)`.
> 

Thanks, saved the day for me.

+1 to some sort of message that this is the problem instead of just hanging...
