### ISSUE TITLE
Feature Request: app.config in azure functions

### ISSUE THREAD

**Issue by shyamal890** [Azure/azure-functions-core-tools#354]
Currently we are utilizing `local.settings.json` for app settings when running the azure function app locally and it fetches settings from the app settings tab in azure portal when in production.

Problems with this approach:

1. How does a referenced assembly (data service) fetch `connection strings`, `app settings` from parent project in local testing and in production?
- This would be addressed if azure functions fetches settings from `web.config` or `app.config` file.

2. Creates confusion as most .NET projects follow `app.config` and `web.config`. People have to informed that `local.settings.json` is just for testing in local environment and that referenced assembly won't look for settings in this file.

**Comment by mikhailshilkov** [comment]
`json`-based settings seem to be the new standard for .NET Core projects, so I guess functions just follow along that trend

**Comment by jeffhollan** [comment]
Yes would agree with @mikhailshilkov here - as far as I know #1 also works today and connection strings and app settings will correctly redirect to fetch from the right source. Have you hit any limitations where this doesn't work?

**Comment by maakku** [comment]
I think I hit a limitation, kinda, not exactly related to the problems mentioned above though. I implemented a wcf proxy for logic apps to call (wsdl had recursive reference in a message response schema -> couldn't use the SOAP connector). I wanted to add wcf message logging but couldn't find a way to do this in code, in app.config it would be easy.

**Comment by ahmelsayed** [comment]
tracked by https://github.com/Azure/azure-functions-host/issues/992

**Comment by manishsg** [comment]
I agree app.config approach should be supported by Azure functions..

**Comment by rlightner** [comment]
@grammophone  Can you give a small example of this?

**Comment by grammophone** [comment]
Of course, @rlightner.

The contents of the ZIP file:

- In `ITraceWriter` interface, we abstract the `TraceWriter`.
- The `MarshalledTraceWriter` is an `ITraceWriter` implementation which can be marshalled by reference accross `AppDomain`s.
- The `IWorker` is a disposable interface abstracting the work to take place. Its single method `DoWork` method takes an `ITraceWriter` argument. But you can define your own interface.
- The `Worker` is an abstract base implementation for `IWorker` which is marshallable by reference accross `AppDomains`. Subclass and override the `DoWork` method.
- The `NopWorker` is an example worker which logs that it does nothing.
- The `WorkerProvider<IW>` provides transparent proxies of objects running in a separate `AppDomain` and implementing a generic `IW` interface.
- `Function1` is a demo Azure Function which uses a `WorkerProvider<IWorker>`  to create a `NopWorker` running in a different `AppDomain` and calls the method `DoWork` on the proxied interface in order to successfully do nothing.

Add an `App.Config` to your project. Good luck!

[FunctionToAppDomain.zip](https://github.com/Azure/azure-functions-core-tools/files/2178370/FunctionToAppDomain.zip)

**Comment by rlightner** [comment]
@grammophone Thank you kindly! Are you doing any type of IoC in your created AppDomain?

**Comment by grammophone** [comment]
@rlightner you are welcome. Yes, the referenced libraries in my function use extensive IoC based on Unity and defined in various .config files, included from the main .config of the running `AppDomain`:
![image](https://user-images.githubusercontent.com/2425684/42485341-ece3a68e-83ff-11e8-8cfb-2097779abf6f.png)
