### ISSUE TITLE
func host start --script-root fails with "Unable to find project root."

### ISSUE THREAD

**Issue by handeeadiguzel** [Azure/azure-functions-core-tools#366]
Version: 2.0.1-beta.22
Running from Windows. 

I don't understand why the first command works but the second one doesn't. I don't see any pattern, I'm running both commands with relative paths:

1. Works from MyFunctions folder: `func host start --script-root .\bin\Debug\netstandard2.0\`

3. Doesn't work: `func host start --script-root .\MyFunctions\bin\Debug\netstandard2.0\`

> Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.

Running the command with absolute path doesn't work either.

**Comment by handeeadiguzel** [comment]
I'm still having the same issue. I wonder if my description wasn't clear enough. Appreciate the help.

**Comment by ahmelsayed** [comment]
I just pushed 1.0.9 to npm and VS feeds. Please update your cli and give it another try. Let me know if you still have an issue

**Comment by ahmelsayed** [comment]
Oops, just realized you are using v2 not v1. I need to prepare a release of the v2 cli. The issue was closed because I checked in the fix, but it hasn't yet been published. I'll update this issue once I have a build ready

**Comment by gabrieljoelc** [comment]
Is there a way we can keep `--script-root` [documentation](https://github.com/Azure/azure-functions-core-tools/commit/50323beaaef1ad61dd0d4c13d7fe606d7cfec51c#diff-d5bd5964e332005d6ac39aa7a8c01037L129) since 50323be is still checking for those two switches?

Does [this](https://github.com/MicrosoftDocs/azure-docs/pull/9699) look accurate based on that change?
