### ISSUE TITLE
Installing CLI 1.0.8 on Win10 (original) breaks tooling

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-core-tools#369]
I have the original version of Windows 10 (my company hasn't authorized the upgrades yet). I was able to successfully download and install Azure Functions CLI 1.0.8, but it fails at run-time, if .NET 4.7.1 isn't installed. But .NET 4.7.1 is only supported for Windows 10 Anniversary Edition and higher.

That means that even though Windows 10 (v1511) is supported until April 2018 and Windows 10 (v1607) is supported until October 2018, the Functions tooling already does not.

Would it be possible to reduce the .NET target framework to .NET 4.6.2?

If not, is there a way to prevent installation of CLI tools that cannot actually be used?

Finally, how do I get back to 1.0.7 for use in VS2017?

**Comment by ahmelsayed** [comment]
/cc @fabiocav  and @paulbatum 

Sorry about that. The CLI move to 4.7.1 is because the runtime itself (which is hosted in the CLI) moved to be 4.7.1 only.  https://github.com/Azure/azure-functions-host/commit/d74bd513283412f84896111f1cb6088b2f49e9bf 

to go back to 1.0.7 go to `C:\Users\<user>\AppData\Local\Azure.Functions.Cli` and delete the 1.0.8 folder.

**Comment by ahmelsayed** [comment]
also I wasn't aware that 4.7.1 requires Windows 10 update. I'm not sure how problematic that is.

**Comment by MisinformedDNA** [comment]
/cc @davidebbo 

Is there a reason 4.7.1 needed to be adopted? There wasn't an attached issue that stated why this was necessary.

**Comment by davidebbo** [comment]
@fabiocav can give details, but yes, there was a specific reason we had to move to 4.7.1. The reason was quite complex, and relates to binding redirects, our ability to create effective ngen binaries (to help cold start).

**Comment by fabiocav** [comment]
I can dive deeper into the details, but the main reason why we had to make that change was to address some issues caused by required binding redirects to support .NET Standard dependencies, redirecting GAC/Framework dependencies to bin. This flow would break the loader preventing native images from being used and significantly impacting the cold start time of the runtime.

**Comment by MisinformedDNA** [comment]
Thanks for the notes. I'll keep harassing and escalating internally. :)

**Comment by MisinformedDNA** [comment]
Per @davidebbo on https://github.com/Azure/azure-functions-host/issues/2381:

> realistically, we just need to move forward and make the Windows update a requirement at this point.
