### ISSUE TITLE
[CoreToolsHost] VS2022 ver.17.11.4 - Debug FunctionApp .NET8 -  An error occurred while running CoreToolsHost.System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by qasimalik786** [Azure/azure-functions-core-tools#3858]
### Version

4.90.0-inprocess

### Description

While debugging Azure Function locally I encountered an issue. Please refer attached file.

![image](https://github.com/user-attachments/assets/34b680e0-0014-42b9-970b-0c78d8e3063b)

### Steps to reproduce

Update the Azure Function Core Toolset and then debug, application will refuse to work as normal

**Comment by mattchenderson** [comment]
Hi @qasimalik786 - thanks for reaching out. Could you please confirm the details of your project? I assume this is .NET 8 on the in-process model. Also, what version of Visual Studio are you using?

If you wouldn't mind trying something out, can you start the project without attaching the debugger? We're aware of an issue with this version that only seems to manifest for some devices when a debugger is attached, though it manifests differently. Still, I'd be curious to know that makes a difference here.

**Comment by qasimalik786** [comment]
Yes, that is correct. And I am using VS2022.

**Comment by mattchenderson** [comment]
I just noticed that is in the updated title - my apologies for missing that before!

**Comment by mattchenderson** [comment]
I believe I know what this is. It looks like there is indeed a bug in logic that was recently added. I believe the absence of a `local.settings.json` file and specifically the absence of `FUNCTIONS_WORKER_RUNTIME` within it to be the cause. We'll work on getting that fixed.

**Comment by qasimalik786** [comment]
> Hi @qasimalik786 - thanks for reaching out. Could you please confirm the details of your project? I assume this is .NET 8 on the in-process model. Also, what version of Visual Studio are you using?
> 
> If you wouldn't mind trying something out, can you start the project without attaching the debugger? We're aware of an issue with this version that only seems to manifest for some devices when a debugger is attached, though it manifests differently. Still, I'd be curious to know that makes a difference here.

I tried but still it's not working.

**Comment by mattchenderson** [comment]
@qasimalik786 My apologies, as I forgot to update this thread with the same information as the other one I saw you participate in - hopefully you saw the updates there. We first rolled back the version to address the issues that people were seeing. Now, we are reintroducing the changes with some fixes that we believe should address the issues you are seeing here.

It is possible that this NullReferenceException has a root cause that would still produce an error. The behavior defaults to the .NET 6 version of the host, unless it can find the relevant settings in `local.settings.json`. If it finds those, it will switch to .NET 8. The NullReferenceException seems like it could be the result of an issue locating or processing those settings. Therefore, you could end up in a situation where a .NET 6 host attempts to load your .NET 8 assemblies. This would lead to something similar to 
>  System.Private.CoreLib: Exception while executing function: Function1. MyFunctionsProject: Could not load file or assembly 'System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

It would be great to know if the latest version works for your scenario - please try it out and let us know! If you do see the .NET 6 version being loaded, it would be great to capture additional information about your project so we can investigate further.
