### ISSUE TITLE
Blobs created via 'func azure functionapp publish' should start with timestamp

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-core-tools#438]
Currently they're random guids, which makes it hard to see history of deployment.

**Comment by ahmelsayed** [comment]
So it was actually [`DateTimeOffset.UtcNow.ToUnixTimeSeconds()-GUID.zip`](https://github.com/Azure/azure-functions-core-tools/blob/4271a4fe40d8fed0f852464d6fb9d50bafffd45d/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionApp.cs#L265) I changed it to `DateTimeOffset.UtcNow.ToString("yyyyMMddHHmmss")-GUID.zip` since that's probably easier to read.

Closed in fb775dc7
