### ISSUE TITLE
javascript not working for me on linux

### ISSUE THREAD

**Issue by jiata** [Azure/azure-functions-core-tools#545]
My Environment:
- Ubuntu 16.04 LTS
- Installed Azure Functions Core Tools using the Apt-get method for linux

Repro steps:
1. in my working dir, create new folder for function and `cd` into it
2. ran `func init -n` as i already have my git project
3. ran `func new` where i selected `javascript`, `http trigger` and name the function `HttpTriggerJS`
4. ran `func start`, stack trace below:

![image](https://user-images.githubusercontent.com/16616215/41727198-c6d1c81c-7541-11e8-951a-9eae2891448a.png)
![image](https://user-images.githubusercontent.com/16616215/41727221-d3b2b67c-7541-11e8-9b12-2f9e34b31430.png)

**Comment by ahmelsayed** [comment]
do you have node on your path?

**Comment by travisnielsen** [comment]
Hah. It turns out I did not. I had the exact same issue as #545 for JavaScript. I fixed the path statement and node / javascript works fine. However, my compiled .net core c# function still fails with the same error.

I can run a new C#-based HTTP trigger. That works. It seems like the issue has something to do with my specific app.

**Comment by travisnielsen** [comment]
I had the same issue and it was resolved by fixing the missing path for Node.
