### ISSUE TITLE
2.1 cli with dependencies on 2.0 packages

### ISSUE THREAD

**Issue by hiraldesai** [Azure/azure-functions-core-tools#558]
Many of the Microsoft extensions repositories have a hard dependecies on 2.0 version even for 2.1 version of CLI. This results in runtime errors because of DLL loading issues and it also prevents users from using some of the features from 2.1 libraries.

![image](https://user-images.githubusercontent.com/1005174/41987531-4df56474-79ee-11e8-984b-68f4c57db0be.png)

Is there a plan to change this dependency to match? Let me know if I'm missing something or doing something completely wrong.

**Comment by ahmelsayed** [comment]
I think all of those were updated in the latest release (https://github.com/Azure/azure-functions-core-tools/releases) Restart your VS and it should prompt you for update

**Comment by hiraldesai** [comment]
Thanks - great timing!

**Comment by hiraldesai** [comment]
Hi @ahmelsayed - I see that the 2.0.1-beta.31 is getting installed in _AppData\Local\AzureFunctionsTools\Releases\2.2.2_ ? Does that mean this will be out of preview soon?
![image](https://user-images.githubusercontent.com/1005174/42070522-accb696c-7b0b-11e8-8a7e-20826a6a44c9.png)

Also - is there a way to track when a given version is available on Azure App Service? I just created a new Functions app in the Azure Portal, set it to beta and it's showing me **Runtime version: 2.0.11888.0 (beta)**.

**Comment by ahmelsayed** [comment]
the versions story is a bit confusing because of the many independent components that make up the product. But those numbers `2.1.0`, `.2.2.2`, etc are just internal numbers used to version the tooling feed. They don't really have any meaning for the product. The you can get the product version by running the cli, the cli also has it's own versioning scheme. But if you run `func.exe` from that folder you should see 


```
Azure Functions Core Tools (2.0.1-beta.31)
Function Runtime Version: 2.0.11888.0
```

**Comment by hiraldesai** [comment]
Thank you for the info Ahmed!
