### ISSUE TITLE
Add the ability to "func host start" a single function

### ISSUE THREAD

**Issue by tdwright** [Azure/azure-functions-core-tools#652]
Sometimes it's useful to run a function in isolation.

It would be great if I could do something like:

`func host start --function "My Function Name"`

Is this a feature that could be considered?

(I suppose this is a bit similar to #303)

**Comment by witek1902** [comment]
Any changes in 2.0 ?

**Comment by gotgenes** [comment]
This would be a very helpful feature to add for testing purposes.

In our case, we have two functions: one that writes to a storage queue, and one that reads from the storage queue. In production, this should be the same queue; thus we want a single Application Setting with the queue name that is used by both functions, to enforce consistency so that we can be assured the writer and reader are both pointed to the same queue.

But during acceptance testing, because both functions are running at the same time, we are forced to connect each function to a different queue, or else the messages produced by our queue writer function will immediately get consumed by the queue reader function. Without the ability to run each function by itself, I don't see a solution other than using two different Application Settings that in production must be checked to make sure they contain the same value.
