### ISSUE TITLE
ExtensionsMetadataGenerator does not include function defined WebJobStartupAttribute

### ISSUE THREAD

**Issue by fbeltrao** [Azure/azure-functions-core-tools#721]
In a Azure Function I have defined a WebJobsStartup. During local development (F5), my startup code gets called. However, when publishing to Azure from Visual Studio/Code my startup code does not execute.

It seems to be a problem with the Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator that generates the file (bin/extensions.json) properly when running locally, but not when publishing to Azure.

Published bin/extensions.json
```json
{
  "extensions":[
    { "name": "CosmosDB", "typeName":"Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null"}
  ]
}
```

extensions.json in debug folder
```json
{
  "extensions":[
    { "name": "DependencyInjectionFunctionStartup", "typeName":"DependencyInjectionFunction.Startup, DependencyInjectionFunction, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "CosmosDB", "typeName":"Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null"}
  ]
}
```

In order to reproduce the problem try to deploy the sample azure function here: https://github.com/fbeltrao/Samples/tree/master/azure-functions-dependencyinjection 
Function to test: (GET) PartsOfDay

Visual Studio Version: 15.9.0 Preview 2.0
Azure Functions Core Tools (2.0.1-beta.38)
Function Runtime Version: 2.0.12050.0

Referenced packages:
```xml
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />
```

**Comment by ankitkumarr** [comment]
I was able reproduce this issue using the VS Code extension. However, running `func azure functionapp publish <app-name>` in the functions project worked fine creating the correct `bin\extensions.json`, so did simply running `dotnet publish`.

This, to me, seems like a VS Code Functions extension issue. @EricJizbaMSFT , would you have any input in this?

**Comment by EricJizbaMSFT** [comment]
I cloned the repo and ran a `dotnet publish`. It's creating the wrong "extensions.json", which makes me think there's nothing VS Code could do in this case. This is what I see:
```
Erics-MacBook-Pro:src ericjizba$ dotnet publish
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  DependencyInjectionFunction -> /Users/ericjizba/Repos/sampleapps/Samples/azure-functions-dependencyinjection/src/bin/Debug/netstandard2.0/bin/DependencyInjectionFunction.dll
  DependencyInjectionFunction -> /Users/ericjizba/Repos/sampleapps/Samples/azure-functions-dependencyinjection/src/bin/Debug/netstandard2.0/publish/
Erics-MacBook-Pro:src ericjizba$ cd /Users/ericjizba/Repos/sampleapps/Samples/azure-functions-dependencyinjection/src/bin/Debug/netstandard2.0/publish/
Erics-MacBook-Pro:publish ericjizba$ cd bin/
Erics-MacBook-Pro:bin ericjizba$ cat extensions.json
{
  "extensions":[
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "CosmosDB", "typeName":"Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null"}
  ]
}
```

As a workaround, you can modify a few things to deploy the result of a build instead of a publish (although I'm not sure I recommend doing that long-term). In `.vscode/settings.json`:
  1. Change "azureFunctions.preDeployTask" to "build"
  1. Change "azureFunctions.deploySubpath" to "bin/Debug/netstandard2.0/"

I would also recommend committing the ".vscode" folder in to source control if you (or any contributors) plan to use VS Code on a regular basis. I used the default generated ".vscode" files, but I'm not sure if you were using the same.

**Comment by ankitkumarr** [comment]
@EricJizbaMSFT  What version of dotnet core sdk did you use? I tried `dotnet publish` on my windows machine once again and I did get the correct "extensions.json". I used version `2.1.400`

**Comment by EricJizbaMSFT** [comment]
```
Erics-MacBook-Pro:src ericjizba$ dotnet --version
2.0.0
```

@ankitkumarr can you post screenshots of your folder structure or copy output of running the same commands I ran above? There's several "extensions.json" files generated at different paths in the "bin" folder so I want to make sure we're talking about the same exact file.

**Comment by EricJizbaMSFT** [comment]
I'm not an expert on the source code for the func cli, but it appears that it's running a `dotnet build` instead of a `dotnet publish`

In `PublishFunctionAppAction.RunAsync`:
https://github.com/Azure/azure-functions-core-tools/blob/617620c4fdf8769335994e3eb57975d0ad3f1cc9/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L125

In `DotnetHelpers.BuildDotnetProject`:
https://github.com/Azure/azure-functions-core-tools/blob/307dbdcd9ebf62d1319865bb449e0f428e1edc00/src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs#L84

To me that explains why the func cli is different than VS Code. Although I really think a `dotnet publish` is the correct option.

**Comment by ankitkumarr** [comment]
@EricJizbaMSFT, thanks for your insight. I am out today and traveling right now. Let me get back to you on Monday with more details.

**Comment by ankitkumarr** [comment]
@EricJizbaMSFT, I apologize! You were right, I wasn't looking at the `extensions.json` under the publish folder after running `dotnet publish`. I was looking at other ones.

In that case, I don't think there's much we can do here. @fbeltrao, I recommend following what Eric said in his first comment. 

As for the cli running `dotnet build` instead of `dotnet publish` during the publish action, @ahmelsayed, should we update the cli to run publish?

**Comment by ahmedelnably** [comment]
This should be resolved by now, please confirm if you are not seeing the error anymore

**Comment by fbeltrao** [comment]
@ahmedelnably yes, this is working now. Thanks!
