### ISSUE TITLE
Unable to follow logs for functions deployed on k8s

### ISSUE THREAD

**Issue by krancour** [Azure/azure-functions-core-tools#753]
Using 2.0.3 on AKS...

For any given function deployed on k8s, I am unable to follow its logs.

For instance, the following works fine and exits 0 immediately, as anticipated:

```
$ k logs getmessages-deployment-5574cb64bc-b7qzb -n azure-functions
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

However, when adding the `-f` flag to follow logs, things go wrong:

```
$ k logs -f getmessages-deployment-5574cb64bc-b7qzb -n azure-functions
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
failed to watch file "/var/log/pods/c7a42e35-c036-11e8-b493-dec1955fcc8b/getmessages-deployment_0.log": no space left on device
```

I have not observed this to be an issue with other workloads running in the same cluster.

**Comment by wittenbergio** [comment]
@krancour did you ever figure this out? Obviously there is no space left in some device, but do you know where? In the Node? In the Pod? Thanks.

**Comment by krancour** [comment]
Nope. Still unresolved.

**Comment by snobu** [comment]
How do you even look at the logs? context.log() in my function doesn't show up in kubectl logs func-pod

**Comment by snobu** [comment]
Ref https://github.com/Azure/azure-functions-host/issues/3469#issuecomment-429183447 for the workaround.

**Comment by ahmelsayed** [comment]
logs should be enabled by default now by setting [this](https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/StaticResources/Dockerfile.python#L4) in the dockerfile.

**Comment by snobu** [comment]
Appreciated. Can we alias that to something shorter somewhere in the future? Looks a bit threateningly long :)

**Comment by krancour** [comment]
@ahmelsayed wouldn't logging to the console be a sensible default for a container? Why does this need to be set explicitly by the user?

Would it make more sense to pre-set this in the next version of the `mcr.microsoft.com/azure-functions/python` image?

**Comment by ahmelsayed** [comment]
The logs can be very verbose and we had a couple of CRIs about these stdout logs filling the disk space when the container was left running for a long time. I’m not sure what’s the right thing here because people will just deploy these containers with the default behavior. I can follow up with the owners of that area to see if they have a better solution now. 

@snobu yeah it would be nice to have that. The runtime uses aspnet core config system which makes env vars look very long. (You should see the array syntax :)). @fabiocav what are your thoughts about this? I know the nice way of setting this is in host.json...
