### ISSUE TITLE
Unable to debug if profile name contains special characters

### ISSUE THREAD

**Issue by TimNilimaa** [Azure/azure-functions-core-tools#768]
I've found that if your windows username contains the Swedish signs Å, Ä or Ö or paranteses '(', ')', you are unable to debug using Visual Studio.
For a flash of a second you get an error message, using screen recorder I managed to read it,
It states that it is unable to find the double_edge.js file located at %localappdata%\AzureFunctionsTools\Releases\1.4.0\cli\edge\double_edge.js

So if your %localappdata% starts with c:\users\tim.nilimaa-svärd or something like that, you will not be able to debug with visual studio.

**Comment by TimNilimaa** [comment]
Error looks to be in module.js at row 471
<img width="427" alt="error" src="https://user-images.githubusercontent.com/6008779/46250235-c5c37800-c436-11e8-9d5f-bca57c022fd4.png">

**Comment by ahmelsayed** [comment]
It's a dup of the one you linked to. The underlying issue is with edgejs which is a dependency of https://github.com/Azure/azure-functions-host/ v1. I don't know if edge or the azure-functions-host repo plans on fixing that, I'd ask over there as I don't believe there is anything that can be done on the core-tools as we just depend on those other packages for v1 javascript functions.
