### ISSUE TITLE
Don't rely on Azure CLI to get access token

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-core-tools#840]
I was looking at how Core Tools depends on the Azure CLI and I noticed that the only thing it's using it for is to get the access token:

https://github.com/Azure/azure-functions-core-tools/blob/60ea24fd4408ea876882324a9505c2d43bb37726/src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs#L72-L96

`az account get-access-token`

A big and quick win for Core Tools would be to get off this dependency so that the entire Azure CLI isn't needed. This will pave the way for when Azure Functions has PowerShell cmdlets for Azure PowerShell.

**Comment by tylerl0706** [comment]
cc @asavaritayal @pragnagopa @joeyaiello @stevel-MSFT

**Comment by monteledwards** [comment]
personally,  i am in favor of this approach and admire it.  let az cli be the central point for authentication. people in azure typically have multiple subscriptions and if i have to set my context on each tool that's not fun,

**Comment by tylerl0706** [comment]
@monteledwards I understand where you're coming from... But az cli and Azure PowerShell don't share the same context. 

There are a large set of users that use Azure PowerShell instead of Azure CLI and to force those users to download another tool just to get an Auth token to use isn't a good practice.

The func cli can follow the standard OAuth 2.0 flow to retrieve the access token from Azure.

**Comment by ahmelsayed** [comment]
That used to be how it worked but there were too many issues trying to do my own authentication and supporting all the various methods and setups Azure has for login so I changed it in d776e404643776ce823e95f6fa35d48252f3d223. Not to mention as @monteledwards mentioned, if I'm doing my own login I have to allow the user to select the account, tenant, subscription, etc which is confusing because it's yet another tool that you'll have to configure that in.  I don't think the core tools shouldn't be in the business of managing Azure resources or login/logout. If you don't have az or don't wanna use az you can always 

```
func ... --access-token {accessToken}

# OR 

echo $token | func ... --access-token-stdin
```

I meant to add support for azure powershell if it's installed to get the token from there as well, but I wasn't clear on how to implement that so I didn't

**Comment by tylerl0706** [comment]
I still don't like the idea of relying on an external tool to retrieve an access token... but I was messing with doing it in Azure PowerShell last week and think this works:

```powershell
$context = Get-AzContext; $context.TokenCache.ReadItems() | ? TenantId -eq $context.TenantId | % { $_.AccessToken }
```

**Comment by ahmelsayed** [comment]
I'm closing this as we don't intend on removing az dependency for azure related operations from the core tools
