### ISSUE TITLE
Don't invoke PyInstaller by default

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#886]
**Problem Statement**

Currently, PyInstaller is invoked by default when publishing a Python app to Azure. This causes issues when using certain packages that are unsupported by PyInstaller. Example: azure-cosmos . Present guidance to users is to use the `--no-bundler` flag to work around this limitation. 

We've received feedback that it is unclear from a user's standpoint what the workflow is, why certain packages should be failing and what the purpose of the --no-bundler flag is. 

**Proposed Solution**

The proposal is to:

1.  **Disable** PyInstaller by default to ensure user success on the first iteration. 
2.  Add a `--bundle-deps` flag to invoke the PyInstaller workflow on an opt-in basis. 
3. As part of documentation - https://github.com/Azure/azure-functions-python-worker/wiki/Developer-Guide , provide information about the flag proposed in the previous step and the workflow associated with that flag. 

/cc @ankitkumarr @ahmelsayed

**Comment by ankitkumarr** [comment]
**Clarification on the current scenario**

The error with azure-cosmos was caused because sub-modules were being ignored by Pyinstaller which is now [fixed](https://github.com/Azure/azure-functions-core-tools/commit/0ff7043cdb27b5248cf07ae1b7103019f7689722).

Right now, if Pyinstaller fails to bundle, core-tools automatically takes the `--no-bundler` path without user having to do anything. Problem comes if Pyinstaller bundles fine but it runs into issues in the runtime (Example - it ignored a package for some reason). As of know, we are not aware of any package that would cause any such error to force users to use `--no-bundler` flag.

However, as discussed offline, given the volatility and the workflow being unclear, I am ok with the proposal and will implement it.

**Comment by ahmelsayed** [comment]
@asavaritayal also keep in mind that the current cold start numbers we have measured and communicated are using pyinstaller. There is an impact on the package size and load time when not using pyinstaller.

**Comment by ankitkumarr** [comment]
@asavaritayal The PR is up. Do we want to recommend people to use the new flag for bundling in the CLI or just in the documentation?

**Comment by asavaritayal** [comment]
Here are some packages from other reports: `gidgethub.sansio` , `typedefs`

**Comment by ankitkumarr** [comment]
I believe the error with those packages were also due to the bug where sub-modules were being ignored that I talked about, which was fixed [here](https://github.com/Azure/azure-functions-core-tools/commit/0ff7043cdb27b5248cf07ae1b7103019f7689722) last week.

**Comment by asavaritayal** [comment]
Closing issue in favor of our discussion today. Instead, let's focus on surfacing more info to the user on publishing - https://github.com/Azure/azure-functions-core-tools/issues/899
