### ISSUE TITLE
Standardize virtual env creation Python Functions

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-core-tools#923]
When `func new` or `func host start` is involved for Python on Functions, it expects a virtual environment. When code is committed, it is not expected to commit the entire virtual environment folder. So here is how this provides a poor dev experience in two aspects

1. DevOps
2. VS Code

### DevOps

Continuous integration on Azure DevOps needs a virtual env to start function and run python tests. So this is manually created by the user in their devops pipeline. If func core tools can enable this based on py3.6, they can standardize the name of the venv to say **worker_env**. That way, this can automatically be added to .gitignore to avoid committing these huge environments (like local-settings.json)

### VS Code

Automatically can create worker_env and add this to gitignore to ensure smoother tooling experience.

At the current moment, CI for Python on functions does NOT take care of virtual environments, and CD takes care (through --build-native-deps)
This is also inconsistent and confusing.

Also Conda support can solve this as well.

**Comment by dirkesquire** [comment]
I think you need to standardise on only two simple aspects to solve a clean build:
Two settings (in a file maybe? azure settings or in a yaml file?) somewhere that contains:
```
REQUIREMENTS=requirements.txt   

PYTHON_VERSION=3.6.7
```

The first is a relative path to the requirements.txt file as absolute path would be different on the Azure server). The second is which python version to use. 
From these two settings, the continuous integration can easily create a worker_env environment all on its own, activate local python version using pyenv if necessary, and then do tests etc. 

### Advantages are: 
a) You are not limiting users to tell them their environment folder has to be named a certain way. Whatever you name it on the build server, the user should not have to care about.
b) You are not tying users to a particular python version 3.6 which quite frankly is a HUGE pain currently since 3.7.1 is out right now, and Azure always seems behind on its python versions. 
c) In most cases the user will no longer even need to worry about creating the environment folder on the server anymore, as the above is all one needs to do so.

### Environment Script
For the server to install the virtual environment it just needs a simple standardised script file which (which I usually call env-install) and does the following:  
a) sees if the environment folder is there, and if not, creates it
b) sees if the environment is active and if not activates it
c) upgrades pip
d) installs all packages in the specified requirements.txt

The script allows the server to re-use the environment folder for speed, and re-running the last two lines multiple times on an existing environment folder is absolutely fine. 

[env-install.txt](https://github.com/Azure/azure-functions-core-tools/files/2710175/env-install.txt)


### Other notes:
VS Code is already brilliant at detecting virtual environments and working with them, so I wouldn't say that VS Code experiences a poor dev experience from this regard.

Generally the environment folder is called 'env' not 'worker_env', so that name is a bit non-standard if users are expected to follow that name on their local machines.

We should avoid forcing users to use specific versions of python. At the time of writing func runtime refuses to work with 3.7.1, which is a problem if that is your current system version of python.

**Comment by asavaritayal** [comment]
Related to https://github.com/Azure/azure-functions-core-tools/issues/1015

**Comment by asavaritayal** [comment]
Closing issue as this should get resolved with the following two work items: 

- https://github.com/Azure/azure-functions-core-tools/issues/1023
- https://github.com/Azure/azure-functions-core-tools/issues/1015

As an FYI, we made the runtime and platform compatible with version 3.7 but have received feedback that 3.7 is not yet supported for a few common ML libraries e.g. Tensorflow. Keeping the feedback in mind, we will defer the upgrade to 3.7
